// Auto-generated inventory of real medical chart PDFs from ~/Downloads/peerspectiv AI docs
// Regenerated by scripts/regenerate-pdf-inventory.mjs
// Total: 84 files, all medical charts grouped by specialty

const BASE = '/Users/dlnagalla/Downloads/peerspectiv AI docs';

export const pdfInventory = {
  medicalCharts: [
    `${BASE}/100013001_OB_Doughtie.pdf`,
    `${BASE}/100025875_OB_Fielder.pdf`,
    `${BASE}/100031645_OB_Doughtie.pdf`,
    `${BASE}/100048191_OB_Fielder.pdf`,
    `${BASE}/100082326_GYN_Doughtie.pdf`,
    `${BASE}/100190770_OB_Fielder.pdf`,
    `${BASE}/100273419_GYN_Fielder.pdf`,
    `${BASE}/100526586_GYN_Doughtie.pdf`,
    `${BASE}/100718028_OB_Doughtie.pdf`,
    `${BASE}/102624398_GYN_Fielder.pdf`,
    `${BASE}/BH Smith 1.pdf`,
    `${BASE}/BH Smith 2.pdf`,
    `${BASE}/BH Zamora-Duprey 1.pdf`,
    `${BASE}/BH Zamora-Duprey 2.pdf`,
    `${BASE}/BH Zamora-Duprey 3.pdf`,
    `${BASE}/Cardiology Khouri 1.pdf`,
    `${BASE}/Cardiology Khouri 2.pdf`,
    `${BASE}/Counselor. Albright. Q4.1.pdf`,
    `${BASE}/Counselor. Albright. Q4.2.pdf`,
    `${BASE}/Counselor. Albright. Q4.3.pdf`,
    `${BASE}/Counselor. Brewers. Q4.1.pdf`,
    `${BASE}/Counselor. Brewers. Q4.2.pdf`,
    `${BASE}/Counselor. Brewers. Q4.3.pdf`,
    `${BASE}/dental 2.pdf`,
    `${BASE}/Dental Garner 1.pdf`,
    `${BASE}/Dental Garner 2.pdf`,
    `${BASE}/Dental Garner 3.pdf`,
    `${BASE}/Dental Nguyen 1.pdf`,
    `${BASE}/Dental Nguyen 2.pdf`,
    `${BASE}/Dental Yellowhair 1.pdf`,
    `${BASE}/Dental Yellowhair 2.pdf`,
    `${BASE}/Dental Yellowhair 3.pdf`,
    `${BASE}/Dental Yellowhair 4.pdf`,
    `${BASE}/Dental Yellowhair 5.pdf`,
    `${BASE}/dental.pdf`,
    `${BASE}/Family Asah 1.pdf`,
    `${BASE}/Family Asah 2.pdf`,
    `${BASE}/Family Bumpus 1.pdf`,
    `${BASE}/Family Bumpus 2.pdf`,
    `${BASE}/Family Coicou 1.pdf`,
    `${BASE}/Family Coicou 2.pdf`,
    `${BASE}/Family Coicou 3.pdf`,
    `${BASE}/Family Coicou 4.pdf`,
    `${BASE}/Family Coicou 5.pdf`,
    `${BASE}/Family. Adee. Q4.1.pdf`,
    `${BASE}/Family. Adee. Q4.2.pdf`,
    `${BASE}/Family. Adee. Q4.3.pdf`,
    `${BASE}/Family. Ahlers. Q4.1.pdf`,
    `${BASE}/Family. Ahlers. Q4.2.pdf`,
    `${BASE}/Family. Ahlers. Q4.3.pdf`,
    `${BASE}/GILMORE 4.pdf`,
    `${BASE}/GILMORE 5.pdf`,
    `${BASE}/GILMORE M6.pdf`,
    `${BASE}/GYN Schultz 1.pdf`,
    `${BASE}/GYN Schultz 2.pdf`,
    `${BASE}/GYN Schultz 3.pdf`,
    `${BASE}/HIV BRIMMER 3.pdf`,
    `${BASE}/HIV BRIMMER 4.pdf`,
    `${BASE}/HIV CLARKE 3.pdf`,
    `${BASE}/HIV MONTREUIL 3.pdf`,
    `${BASE}/Mental Health. Concepcion. Q4.1.pdf`,
    `${BASE}/Mental Health. Concepcion. Q4.2.pdf`,
    `${BASE}/Mental Health. Concepcion. Q4.3.pdf`,
    `${BASE}/Mental Health. Concepcion. Q4.4.pdf`,
    `${BASE}/Mental Health. Concepcion. Q4.5.pdf`,
    `${BASE}/Mental Health. Mateo. Q4.1.pdf`,
    `${BASE}/Mental Health. Mateo. Q4.2.pdf`,
    `${BASE}/Mental Health. Mateo. Q4.3.pdf`,
    `${BASE}/Mental Health. Mateo. Q4.4.pdf`,
    `${BASE}/Mental Health. Mateo. Q4.5.pdf`,
    `${BASE}/MONTREUIL 1.pdf`,
    `${BASE}/MONTREUIL 2.pdf`,
    `${BASE}/MONTREUIL 4.pdf`,
    `${BASE}/MONTREUIL 5.pdf`,
    `${BASE}/OB. Blackham. Q1.2combined.pdf`,
    `${BASE}/OB. Gekas. Q1.1combined.pdf`,
    `${BASE}/OB. Gekas. Q1.2combined.pdf`,
    `${BASE}/OBGYN Francis 1.pdf`,
    `${BASE}/OBGYN Francis 2.pdf`,
    `${BASE}/OBGYN Gogol 1.pdf`,
    `${BASE}/OBGYN Gogol 2.pdf`,
    `${BASE}/Pediatrics Schwartz 1.pdf`,
    `${BASE}/Pediatrics Schwartz 2.pdf`,
    `${BASE}/Pediatrics Schwartz 3.pdf`,
  ],
  reviewForms: [],
  contracts: [],
  reports: [],
  rosters: [],
};

// Map filename prefix to specialty for AI analysis context.
// Covers the expanded reviewer roster (BH, Cardiology, HIV, Mental Health,
// OBGYN, numbered OB/GYN chart IDs, Dental, Family, etc.).
export function getSpecialtyForFile(filePath: string): string {
  const raw = filePath.split('/').pop() ?? '';
  const name = raw.toLowerCase();

  // Numbered chart IDs: "100013001_OB_Doughtie.pdf", "100082326_GYN_Doughtie.pdf"
  if (/^\d+_ob_/i.test(raw)) return 'OB/GYN';
  if (/^\d+_gyn_/i.test(raw)) return 'OB/GYN';

  // BH / Mental Health / Counselor => Behavioral Health
  if (name.startsWith('bh ')) return 'Behavioral Health';
  if (name.startsWith('mental health')) return 'Behavioral Health';
  if (name.startsWith('counselor')) return 'Behavioral Health';

  // Cardiology
  if (name.startsWith('cardiology')) return 'Cardiology';

  // HIV
  if (name.startsWith('hiv ')) return 'HIV';

  // OB/GYN family
  if (name.startsWith('obgyn')) return 'OB/GYN';
  if (name.startsWith('gyn')) return 'OB/GYN';
  if (name.startsWith('ob ') || name.startsWith('ob.')) return 'OB/GYN';

  // Dental (incl. lowercase "dental.pdf" / "dental 2.pdf")
  if (name.startsWith('dental')) return 'Dental';

  // Pediatrics
  if (name.startsWith('pediatrics')) return 'Pediatrics';

  // Family Medicine
  if (name.startsWith('family')) return 'Family Medicine';

  // Fallback for loose names like GILMORE / MONTREUIL
  return 'Family Medicine';
}
